# Default options used for lines
# Reload the plugins config files with /lineation config reload
# Prevent someone from winning multiple times set maxwins
# This can be set in game with /lination config maxwins INT
# Set to 0 to disable.
# Players wins can be wiped with /lineation config forget USERNAME
linedefaults:
  option:
    blocksequence: glass, red_stained_glass, yellow_stained_glass, lime_stained_glass
    messagereach: '250'
    maxwinners: 3
    commands: []
    gamemodes: SURVIVAL,ADVENTURE
maxwins: 0
