# Default options used for lines
# Reload the plugins config files with /lineation config reload
linedefaults:
  option:
    blocksequence: glass, red_stained_glass, yellow_stained_glass, lime_stained_glass
    messagereach: '250'
    maxwinners: 3
    commands: []
    gamemodes: SURVIVAL,ADVENTURE
# Prevent someone from winning multiple times set maxwins
# This can be set in game with /lineation config maxwins INT
# Set to 0 to disable.
# Players wins can be wiped with /lineation config forget USERNAME
maxwins: 0
# Info messages when doing certain actions to guide you through creating a line 
# true/false
guides: true
