name: Lineation
description:  Minecraft Spigot plugin for managing start and finish lines
author: diademiemi
version: 1.1.1
main: me.diademiemi.lineation.Lineation
api-version: 1.16
depend: [WorldEdit]
commands:
  lineation:
    description: Command for Lineation. Type /lineation help for more.
    usage: /<command>
    aliases: [ln]
