# This workflow creates the javadoc and publishes it to GitHub Pages

name: Generate Javadoc and publish to gh-pages

on: 
  release:
    types: [published]
  workflow_dispatch:


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Generate javadocs
      run: |
       ./gradlew javadoc
       mkdir public
       mv build/docs/javadoc public/
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: public
        keep_history: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
